### ISSUE TITLE
Running with HA in a Docker Container

### ISSUE THREAD

**Issue by markrennie71** [SavageCore/HA_Addons#14]
Hello

Is there anyway to run this in my Home Assistant Docker setup please? Since I use Docker containers I don't have the option for add ons.

Cheers
Mark

**Comment by SavageCore** [comment]
I shall investigate this and update here in the next couple of days. The issue will be installing `chromium` and `chromium-chromedriver` for `selenium`...

**Comment by SavageCore** [comment]
This other repo should work for you? They get around the idea by having the "server" talking to Amazon being completely separate, you can run that as another container in your setup. The HA side is just a custom_component.

https://github.com/madmachinations/home-assistant-alexa-shopping-list

**Comment by markrennie71** [comment]
nice one, thank you

**Comment by bachoo786** [comment]
> nice one, thank you

Hi @markrennie71  did you ever manage to get it to work in a docker container?
